$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Train a model to predict busyness in a region based on restaurant data.

display_name: region-busyness-predictor-train-pipeline
experiment_name: region-busyness-predictor-train-experiment

jobs:

  full_pipeline:
    type: command
    inputs:
      config_file:
        type: uri_file
        path: src/configs/train_config.yaml
    code: src
    environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
    compute: azureml:spn-compute
    command: >-
      python main.py
      --config ${{inputs.config_file}}