$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Train a model to predict busyness in a region based on restaurant data.

display_name: region-busyness-predictor-train-pipeline
experiment_name: region-busyness-predictor-train-experiment

jobs:

  pretrain_job:
    type: command
    inputs:
      config_file:
        type: uri_file
        path: src/configs/train_config.yaml
    outputs:
      output_data_path:
        mode: upload
      output_model_path:
    code: .
    environment: azureml:rbp-env1:7
    compute: azureml:spn-compute
    command: >-
      python src/pretraining_pipeline.py
      --config ${{inputs.config_file}}
      --output_model_path ${{outputs.output_model_path}}
      --output_data_path ${{outputs.output_data_path}}

  train_job:
    type: command
    inputs:
      config_file:
        type: uri_file
        path: src/configs/train_config.yaml
      training_data: ${{parent.jobs.pretrain_job.outputs.output_data_path}}
    outputs:
      model_output:
    code: .
    environment: azureml:rbp-env1:7
    compute: azureml:spn-compute
    command: >-
      python src/train.py
      --config ${{inputs.config_file}}
      --training_data ${{inputs.training_data}}
      --model_output ${{outputs.model_output}}



