# data:
#   file_path: 'azureml://subscriptions/32daaf9e-fc90-446c-8950-13de434a7828/resourcegroups/ml/workspaces/ml-ws/datastores/rbpdatastore/paths/final_dataset.csv'
  
#   raw_data:
#       path: 'azureml://datastores/rbpdatastore/paths/final_dataset.csv'
#       type: uri_file

# azure:
#   workspace: 'ml-ws'
#   resource_group: 'ml'
#   subscription_id: '32daaf9e-fc90-446c-8950-13de434a7828'
#   datastore_name: 'rbpdatastore'
#   dataset_name: 'final_dataset.csv'
#   compute_target: 'spn-compute'

features:
  k: 5
  resolution: 7
  R: 6372.8
  save_pipeline: True
  dir_path: 'models/pretrain/'
  feature_output_filename: 'feature_dataset.csv'
  feature_pipeline_filename: 'full_pretrain_pipeline.pkl'

model:
  train_features: ['dist_to_restaurant', 'Hdist_to_restaurant', 'avg_Hdist_to_restaurants',
                    'date_day_number', 'restaurant_id', 'clusters_embedding', 'h3_index',
                    'date_hour_number','restaurants_per_index']
  target_features: ['orders_busyness_by_h3_hour']
  test_size: 0.33
  model_params: {
    'max_depth': [4,5],
    'min_samples_leaf': [50,75],
    'n_estimators': [100,150],
    }
  n_jobs : 1
  use_grid_search: True
  save_model: True
  dir_path: 'models/train/'
  rf_model_output_filename: 'rf_model.pkl'
  gs_model_output_filename: 'gs_model.pkl'
  mlflow_model_name: 'rbp-model'
  mlflow_artifact_path: 'rbp-model-artifacts'



