name: training_workflow

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - training/**
      - .github/workflows/training_workflow.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: run job
      run: az ml job create --file train_pipeline.yml -g ${{secrets.AZURE_ML_RESOURCE_GROUP}} -w ${{secrets.AZURE_ML_WORKSPACE}}
