name: rbp-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - h3==4.2.2
      - inflect==7.5.0
      - joblib==1.4.2
      - numpy==2.2.4
      - pandas==2.2.3
      - PyYAML==6.0.2
      - scikit_learn==1.6.1
      - mlflow==2.21.3
      - azureml-mlflow==1.60.0
      - fsspec
      - azureml-inference-server-http
      - inference-schema
      - azureml-core
      - azure-ai-ml
